ctrl_interface=/run/wpa_supplicant
update_config=1

# Add a network block on the target with your own credentials.
#
# network={
#     ssid="YOUR_WIFI_SSID"
#     psk="YOUR_WIFI_PASSWORD"
#     key_mgmt=WPA-PSK
# }
